/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "helloservice_constants.h"

namespace helloservice {

const helloserviceConstants g_helloservice_constants;

helloserviceConstants::helloserviceConstants() {
}

} // namespace

