/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef helloservice_CONSTANTS_H
#define helloservice_CONSTANTS_H

#include "helloservice_types.h"

namespace helloservice {

class helloserviceConstants {
 public:
  helloserviceConstants();

};

extern const helloserviceConstants g_helloservice_constants;

} // namespace

#endif
